### PR TITLE
OnEnd event in Xamarin.Forms' AnimationView

### PR DESCRIPTION
**Pull request by MarcosCobena**
Hi!

Our project needs to notice when a Lottie anim. just ends, so made a few changes to support it on Android and iOS. I'm making this PR to know:
- whether this sounds good for you all, and in such case
- whether UWP is mandatory too to merge it finally

Currently OnEnd fires when looping is disabled (at least on Android), but could be worked out to support it too.

Thanks in advance, good work bringing this to Xamarin :-)

PS: I've updated Forms sample to showcase this new thing.

Marcos

### CODE REVIEW

**Comment by martijn00** [comment]
This change looks good, i'm just not sure about the naming convention `FireOnEnd`. What about just `Finished`?

**Comment by modplug** [comment]
I would like to see this as a bindable command as well. Not just an event 👍

**Comment by MarcosCobena** [comment]
Thanks everyone for your comments!

@martijn00 FireOnEnd() is just the public method in charge of actually triggering the event; however, OnEnd is the actual one –I tried to make it familiar along with OnPlay and OnPause. I agree on changing it to Finished() but just wanted to double check the former.

@modplug I believe we can currently turn the event into a Command through a Behavior, although I can do it as well too. I just feel that providing such as a Command but having the other ones (Play & Pause) as events might feel odd. What do you thing guys?

**Comment by modplug** [comment]
I don't agree as Play() and Pause notifies the view and a PlaybackCompletedCommand would notify the ViewModel via binding. Have a look at https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Forms/CachedImage.cs for inspiration

**Comment by MarcosCobena** [comment]
I got your idea @modplug, and agree with it. Just wanted to mention current AnimationView exposes 2 events: OnPlay and OnPause which can be subscribed to be notified in the code-behind, for instance.

However, I agree OnEnd is a little bit different, since you just want the View-VM communication. I'll add it! 

Thanks for your comments.

**Comment by modplug** [comment]
Great @MarcosCobena. Maybe you can add OnPlay and OnPlay as commands as well? It does make sense to expose them as commands if you want to be able to react to it in the view model

**Comment by martijn00** [comment]
And can you rebase your branch to get rid of the conflict?

**Comment by MarcosCobena** [comment]
OK guys I think everything's in place now:
- I've renamed OnEnd to OnFinish because of,
- I've added FinishedCommand, along with PlayingCommand

I didn't add PausedCommand because I actually did it but found a different behavior between Android and iOS:
- in Android pausing the animation and playing it back restarts it completely; however,
- in iOS doing the same just resumes it where it was stopped

Also, pausing in Android currently fires OnFinish/FinishedCommand, so just wanted to discuss this before and maybe improve it in a future PR.

I've put some love in the MainPage as the slider was being hidden in Android, and you'll find too 2 convenient buttons at the top: Play & Pause :-)

Hope you like it! And thanks again for your comments!

**Comment by modplug** [comment]
@MarcosCobena good job. I would like to see UWP support for this before it gets merged. I think it's important to keep the different platforms aligned. I would also suggest that you change the name of the properties to be:

FireOnPlay = PlaybackStarted
FireOnFinish = PlaybackFinished
PlayingCommand = PlaybackStartedCommand
FinishedCommand = PlaybackFinishedCommand

Keep up the good work

**Comment by MarcosCobena** [comment]
@modplug done! I've aligned UWP –although am not super-happy with the approach, but it's the farthest we can go AFAIK without touching LottieUWP. Also, have renamed things as you proposed.

**Pull request merged**
