### PR TITLE
Updates to Lottie iOS 1.0.5

### PR DESCRIPTION
**Pull request by fabionuno**

### CODE REVIEW

**Comment by alexsorokoletov** [comment]
@fabionuno where do you guys find 1.0.5 version of `lottie-ios`?
Cococapods shows 1.0.4 available
screenshot 2017-02-24 14 08 29

https://github.com/CocoaPods/Specs/tree/master/Specs/7/1/d/lottie-ios

**Comment by fabionuno** [comment]
@alexsorokoletov  The [package.json](https://github.com/airbnb/lottie-ios/blob/master/package.json#L3 ) file displays the version as 1.0.5 but the [lottie-ios.podspec](https://github.com/airbnb/lottie-ios/blob/master/lottie-ios.podspec) show 1.0.4.
Taking into account the last commit date of `lottie-ios.podspec` file, I believe it may be outdated.

**Comment by fabionuno** [comment]
To tell the truth they should have switched to version 2.0.0 when renamed the classes and broke compatibility with the previous version

**Comment by martijn00** [comment]
I've published the update on Nuget, and updated Forms as well!

**Comment by fabionuno** [comment]
@alexsorokoletov Having different class names, we will deliver a worst experience than the break of compatibility.
We need to stay as close as possible to the original library.

**Pull request merged**
