### PR TITLE
[WIP] Add support for .NET Standard 2.0

### PR DESCRIPTION
**Pull request by martijn00**
Due to multiple bugs in Xamarin and Visual Studio this can't be released yet.

- VS4Mac doesn't build multi-target projects
- VS2017 doesn't build iOS, tvOS or MacOS binding projects

### CODE REVIEW

**Comment by martijn00** [comment]
@fabionuno can you take a look at this as well?

**Comment by ghuntley** [comment]
Subscribing :-)

**Comment by fabionuno** [comment]
Hi @martijn00 
I haven't access to a Windows machine now to test this and I haven't had contact yet with multi-target projects.

Trying to build the Lottie.Forms in VS4Mac i'm getting this error:

`Package Xamarin.Android.Support.Design 26.1.0.1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Xamarin.Android.Support.Design 26.1.0.1 supports: monoandroid80 (MonoAndroid,Version=v8.0) (NU1202) (Lottie.Forms)`

This is caused by this bug: [53148 - PackageReference does not respect condition](https://bugzilla.xamarin.com/show_bug.cgi?id=53148)

I was able to bypass this error using` Choose/When` tags instead of the `Condition` attribute. 
```xml
<ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="2.5.0.122203" />
</ItemGroup>
<Choose>
    <When Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
        <ItemGroup>
            <Compile Include="Platform\Netstandard\**\*.cs" />
        </ItemGroup>
    </When>
    <When Condition=" '$(TargetFramework)' == 'net461' ">
        <ItemGroup>
            <Compile Include="Platform\Net461\**\*.cs" />
        </ItemGroup>
    </When>
        ....
</Choose>
```

Now building the Lottie.Forms inside VS4Mac, I'm getting just a `bin\netstandard2` folder with `Lottie.Forms.deps.json`, `Lottie.Forms.dll `and `Lottie.Forms.pdb`.

What is the expected behavior after performing a build of Lottie.Forms?

**Comment by martijn00** [comment]
@fabionuno Also see: https://twitter.com/mhvdijk/status/966303220493619200

VS4Mac is just not supported at the moment. On Windows it fails to load the mac project, and doesn't build iOS or tvOS bindings.

I can release new versions of the native bindings, but there is no way i can release .NET Standard at the moment.

**Comment by biapar** [comment]
Hi,
Any updates?
Because .net standard 2.0 is default for new Xamarin Projects.

**Comment by raylight75** [comment]
Clear new solution and not working 
Error	NU1202	Package Com.Airbnb.Android.Lottie 2.7.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). 
Package Com.Airbnb.Android.Lottie 2.7.0 supports: monoandroid81 (MonoAndroid,Version=v8.1)

:)) Sorry, after restart everythink is ok

**Pull request closed without merging**
