### PR TITLE
Added awaitable async overloads for asynchronous methods

### PR DESCRIPTION
**Pull request by fabionuno**

### CODE REVIEW

**Comment by martijn00** [comment]
Awesome! Thanks!

**Comment by modplug** [comment]
Hi @fabionuno. I would love to see this as an interface with an iOS implementation for it as well.
The main reason is that it gets hard to maintain all the different projects if the API's are different.

**Comment by fabionuno** [comment]
Sorry @martijn00 I haven't seen that you have changed the default branch to develop and I sent the PR to the master branch.

**Comment by martijn00** [comment]
Don't worry, i've merged it into develop now.

**Pull request merged**
