### PR TITLE
Fix linker issue by upgrading Xamarin.AndroidX.AppCompat

### LINKED ISSUE #398: AndroidX.Collection dependency error.
## 🐛 Bug Report

Severity	Code	Description	Project	File	Line	Suppression State
Error		Mono.Linker.MarkException: Error processing method: 'AndroidX.Collection.SparseArrayCompat Com.Airbnb.Lottie.LottieComposition::get_Characters()' in assembly: 'Lottie.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve AndroidX.Collection.SparseArrayCompat
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	ChartBuilder.XForms.Android	

### Expected behavior

Lotie package should be compatible with the latest AndroidX Libraries.

### Reproduction steps

1. Update AndroidX packages to the latest 
2. Build for release 
3. the app fails to build for release but builds for debug only. 

### Configuration

**Version:** 4.1.0

**Platform:** 
- [ ] :iphone: iOS
- [X ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X ] :monkey: Xamarin.Forms

### PR DESCRIPTION
**Pull request by angularsen**
Fixes #398

Related:
#397
https://github.com/xamarin/AndroidX/issues/821

After upgrading AndroidX packages in our Xamarin Forms Android project, the linker fails on LottieXamarin using some outdated version of AndroidX types.

```
Error Mono.Linker.MarkException: Error processing method: 'AndroidX.Collection.SparseArrayCompat Com.Airbnb.Lottie.LottieComposition::get_Characters()' in assembly: 'Lottie.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve AndroidX.Collection.SparseArrayCompat
```

### Changes
- Update `Xamarin.AndroidX.AppCompat` from 1.3.1.3 to 1.6.1.6
- Change Android target from monoandroid10.0 to monoandroid12.0 to support newest AndroidX package

### Notes
This needs some assistance to fit into the latest changes of `develop` with net6.0 / maui. I'm not sure if this is experimental or not, but I was not able to build it.

The PR is currently based on the commit prior to net6.0 / maui update, since our team is currently stuck on standard Xamarin Forms for some time and it solves our need. Maybe we can multi-target both monoandroid12.0 and android-net6.0 to continue support for old Xamarin?

### CODE REVIEW

**Comment by angularsen** [comment]
Just a heads up, but I will not be pursuing this PR as we switched to another library instead. 

https://github.com/mono/SkiaSharp.Extended (must use prerelease nugets as of now)

This article was helpful although it explains for MAUI:
https://cedricgabrang.medium.com/implementing-lottie-animations-in-your-net-maui-application-62bd484af651


I'll leave the PR open for anyone stumbling into this later or if you wish to take over the PR.

**Review by malo-bo — APPROVED** [review]

**Comment by malo-bo** [comment]
@martijn00 , please consider updating using this PR

**Comment by logikonline** [comment]
Someone merge this and release it - it takes no effort to resolve this

**Comment by JoelRamosM** [comment]
Pleaase... Someone merge this and release it.  @malo-bo  can i replicate this PR?

**Comment by georgeemr** [comment]
Please I need this PR too

**Comment by JoelRamosM** [comment]
@martijn00  whats is the process to release it? there's some CI/CD automation that do i t?

**Comment by softlion** [comment]
try this gist instead:

https://gist.github.com/softlion/fad8ab6a37809e169d4fcc6b81b0f57b

**Pull request merged**
