### PR TITLE
Possible nullRef fix

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
https://github.com/martijn00/LottieXamarin/issues/181

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
Was it incorrect fix? @martijn00 

OnElementChanged
You made the same check

image

**Comment by martijn00** [comment]
I already did this on: https://github.com/martijn00/LottieXamarin/commit/1385d06477374a4d6d033684d828590ff951ff45

I'm not sure why 2.6.2 is not working, so i need to look at that some time later. Let me know if you have an idea about that.

**Comment by martijn00** [comment]
@AndreiMisiukevich Can you check with 2.6.3?

**Comment by AndreiMisiukevich** [comment]
@martijn00 not me) another guy)

**Pull request closed without merging**
