### PR TITLE
[WIP]Use latest Microsoft `Lottie-Windows` toolkit for Windows renderer 

### PR DESCRIPTION
**Pull request by KSemenenko**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Use latest Microsoft `Lottie-Windows` toolkit for Windows renderer #218

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines 
- [ ] Relevant documentation was updated
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by martijn00** [comment]
@KSemenenko Nice!!! I like this! What do you need to finish it up?

**Comment by azchohfi** [comment]
Yes, please! Move away from my old, unsupported code! 😅

**Comment by KSemenenko** [comment]
Hi @martijn00, I have issue with build, and Nuget https://www.nuget.org/packages/Microsoft.UI.Xaml
I'm still working on a renderer, but I would be very grateful if you help me with the dependencies and build.

**Comment by KSemenenko** [comment]
Hi @martijn00 can you please check it?
Unfortunately at the moment there is no way to know the current progress. so this is not in the Renderer now :(

**Comment by KSemenenko** [comment]
@azchohfi your code looked better.
In addition, the new api does not have information about the current progress.

**Comment by azchohfi** [comment]
"My code" was a port from the Android version, which had a very high CPU cost. This new version is infinitely more performant and is officially supported by Microsoft. @sohchatt, do you know if this is on the plan to support?

**Comment by sohchatt** [comment]
I believe that (all of) the Xamarin and React-Native wrapper APIs can be mapped to with the latest metadata feature being added to Lottie-Windows: https://github.com/windows-toolkit/Lottie-Windows/issues/100

@KSemenenko would you mind starting this discussion on the Lottie-Windows repo so others (not on this repo) can also participate?

**Comment by martijn00** [comment]
@KSemenenko Thanks! I've merged and done some nuget fixes. The new version is now on nuget!

**Comment by KSemenenko** [comment]
@martijn00 thanks you too!
I will still test the implementation, if I find how to improve it, I will make a new PR :)

**Pull request merged**
