### PR TITLE
Update to Lottie Android 3.0.3-support

### PR DESCRIPTION
**Pull request by fabionuno**
Update the Android binding to Lottie 3.0.3 compatible with Android Support packages;

### CODE REVIEW

**Comment by martijn00** [comment]
@fabionuno thanks! I'll look into releasing an update. Did you get anywhere with the iOS version with Swift?

**Comment by FlavioGoncalves-Cayas** [comment]
@martijn00 It would be nice to get a new release in the near future. My animation is not working with the 2.7.1 NuGet-Package, but when I build the current develop-Branch compatible with Lottie-Android 3.0.3, the animation works. However, I would prefer to work with an officially released NuGet-Package.
Thank you.

**Comment by martijn00** [comment]
@FlavioGoncalves-Cayas will do soon.

**Comment by martijn00** [comment]
It's done

**Pull request merged**
